baseurl = "https://chrisrussell.blog/"
DefaultContentLanguage = "en"
Title = "Life So Far // Days Ahead"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; 2020"

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1

# Google Analytics API key.
googleAnalytics = "AIzaSyB73Pbi3HPwOMq6Lk2xyscb1xZVYL0--no"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[params]
  RSSLink = "/index.xml"
  paginate = 10
  custom_css = ["/css/custom.css"]
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  twitter = "chrisrusselljr"
 # facebook = "Your Facebook username"
  instagram = "its_crussell"
 github = "cbrussell"
 # gitlab = "Your GitLab username"
 # npm = "Your npm username"
 # codepen = "Your CodePen username"
 # dribbble = "Your Dribbble username"
 # fivehundredpx = "Your 500px username" # 500px
 # flickr = "Your Flickr username"
 # pinterest = "Your Pinterest username"
 # tumblr = "Your Tumblr username"
 # vimeo = "Your Vimeo username"
 # youtube = "Your YouTube username"
  linkedin = "chrisrusselljr"
 # medium = "chrisrusselljr"
 # strava = "Your Strava userid"
  # Disqus shortname
 # disqus = ""
  author = "Chris Russell"
 authorwebsite = "chrisrussell.blog"
  avatar = "/avatar.jpeg"
  contact = "mailto:chris.russell02@gmail.com"
  bio = "Innovator // Engineer // Artist"
  # Short subtitle/tagline. This is displayed in the header.
 # subtitle = "subtitle"
  # Logo image. This is displayed ogp image.
  logo = "/avatar.jpeg"
  favicon = "/favicon.ico"
    sitename = "Life So Far // Days Ahead"

[[menu.main]]
    name = "Posts"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2
 

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4 

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
